// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    GET_INFO_URI: "/v3/user/get_info",
    GET_MULTI_INFO_URI: "/v3/user/get_multi_info",
    SET_ACHIEVEMENT_URI: "/v3/user/set_achievement",
    GET_GAMEBAR_RANKLIST_URI: "/v3/user/get_gamebar_ranklist",
    BUY_PLAYZONE_ITEM_URI: "/v3/user/buy_playzone_item",
    GET_PLAYZONE_USERINFO_URI: "/v3/user/get_playzone_userinfo",
    SEND_GAMEBAR_MSG: "/v3/user/send_gamebar_msg",
    IS_LOGIN_URI: "/v3/user/is_login",
    TOTAL_VIP_INFO_URI: "/v3/user/total_vip_info",
    IS_VIP_URI: "/v3/user/is_vip",
    FRIENDS_VIP_INFO_URI: "/v3/user/friends_vip_info",
    IS_SETUP_URI: "/v3/user/is_setup",
    GET_APP_FRIENDS_URI: "/v3/relation/get_app_friends"
  };

}).call(this);
