// Generated by CoffeeScript 1.8.0

/*
 * 支付相关的接口
 */

(function() {
  var RequestUrIs, buyPlayzoneItem, debuglog, getPlayzoneUserinfo, helps, request, _makeReqOptions;

  debuglog = require("debug")("wanba_tools::users");

  request = require('request');

  RequestUrIs = require("../enums/request_uris");

  helps = require("../utils/helps");

  _makeReqOptions = helps.makeReqOptions;


  /*
   * 积分购买道具
   * params 同getInfo
   *   zoneid 是  int 区ID，用于区分用户是在哪一款平台下(Android、IOS等)?这个说明有歧义：怀疑应该是应用的分区（默认1）
   *   itemid 是  string  道具ID
   *   count  否  int 兑换道具数量
   * return  见API http://wiki.open.qq.com/wiki/v3/user/buy_playzone_item
   *   吐槽：奇葩的腾讯， API中得返回参数竟然和实际不一样？
   */

  buyPlayzoneItem = function(params, method, callback) {
    var options;
    if (method == null) {
      method = 'POST';
    }
    options = _makeReqOptions(this, RequestUrIs.BUY_PLAYZONE_ITEM_URI, method, params);
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      return callback(null, body);
    });
  };


  /*
   * 查询达人信息
   * params 同getInfo
   *   zoneid 是  int 区ID，用于区分用户是在哪一款平台下(Android、IOS等)?这个说明有歧义：怀疑应该是应用的分区（默认1）
   *
   * return 见API http://wiki.open.qq.com/wiki/v3/user/get_playzone_userinfo#3_.E7.A4.BA.E4.BE.8B.E4.BB.A3.E7.A0.81
   *
   */

  getPlayzoneUserinfo = function(params, method, callback) {
    var options;
    if (method == null) {
      method = 'POST';
    }
    options = _makeReqOptions(this, RequestUrIs.GET_PLAYZONE_USERINFO_URI, method, params);
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      return callback(null, body);
    });
  };

  module.exports = {
    buyPlayzoneItem: buyPlayzoneItem,
    getPlayzoneUserinfo: getPlayzoneUserinfo
  };

}).call(this);
