// Generated by CoffeeScript 1.8.0

/*
 * /v3/relation 下的接口
 */

(function() {
  var RequestUrIs, debuglog, getAppFriends, helps, request, _makeReqOptions;

  debuglog = require("debug")("wanba_tools::users");

  request = require('request');

  RequestUrIs = require("../enums/request_uris");

  helps = require("../utils/helps");

  _makeReqOptions = helps.makeReqOptions;


  /*
   * 获取已安装应用的好友列表
   * return
   * {
   * "ret":0,
   * "is_lost":0,
   * "items":[
   * {"openid":"9CE729C9927532BABBB57F6AB000925B"},
   * {"openid":"08B8273CACFBE0D9F57CAB4E7D8BDBF0"}
   * ]
   * }
   */

  getAppFriends = function(params, callback) {
    var options;
    options = _makeReqOptions(this, RequestUrIs.IS_LOGIN_URI, "POST", params);
    console.dir(options);
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      console.dir(body);
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      return callback(null);
    });
  };

  module.exports = {
    getAppFriends: getAppFriends
  };

}).call(this);
