// Generated by CoffeeScript 1.8.0

/*
 * /v3/relation 下的接口(关系链类)
 */

(function() {
  var RequestUrIs, debuglog, getAppFriends, getRcmdFriends, helps, isFriend, request, _makeReqOptions;

  debuglog = require("debug")("wanba_tools::relations");

  request = require('request');

  RequestUrIs = require("../enums/request_uris");

  helps = require("../utils/helps");

  _makeReqOptions = helps.makeReqOptions;


  /*
   * 获取已安装应用的好友列表
   * return
   * {
   * "ret":0,
   * "is_lost":0,
   * "items":[
   * {"openid":"9CE729C9927532BABBB57F6AB000925B"},
   * {"openid":"08B8273CACFBE0D9F57CAB4E7D8BDBF0"}
   * ]
   * }
   */

  getAppFriends = function(params, method, callback) {
    var options;
    options = _makeReqOptions(this, RequestUrIs.GET_APP_FRIENDS_URI, method, params);
    console.dir(options);
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      console.dir(body);
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      return callback(null, body);
    });
  };

  isFriend = function(params, method, callback) {
    var options;
    options = _makeReqOptions(this, RequestUrIs.IS_FRIEND_URI, method, params);
    request(options, function(err, res, body) {
      var result;
      if (err != null) {
        return callback(err);
      }
      console.dir(body);
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      result = {
        is_friend: body.is_friend > 0,
        is_gamefriend: body.is_gamefriend > 0
      };
      return callback(null, result);
    });
  };


  /*
   * 为用户推荐选择的好友
   *   调用本接口前，请按照模版提交API接口权限申请（申请方式详见这里），以获取接口调用权限。
   *   具体见：http://wiki.open.qq.com/wiki/v3/relation/get_rcmd_friends
   *
   * params:
   *   installed 必须  string  标识需要获取的推荐好友是否已安装应用。
   *     0：获取的均为未安装应用的好友；
   *     1：获取的均为已安装应用的好友；
   *     2：获取所有推荐好友，不区分是否安装应用。
   *
   * return：
   *   items 获取的推荐好友信息。最多可获取50个推荐好友信息。
   *   openid  好友对应的唯一ID。
   */

  getRcmdFriends = function(params, method, callback) {
    var options;
    options = _makeReqOptions(this, RequestUrIs.GET_RCMD_FRIENDS_URI, method, params);
    request(options, function(err, res, body) {
      if (err != null) {
        return callback(err);
      }
      console.dir(body);
      if ((body.ret != null) && body.ret !== 0) {
        return callback(new Error("errCode: " + body.ret + " message: " + body.msg));
      }
      return callback(null, body);
    });
  };

  module.exports = {
    getAppFriends: getAppFriends,
    isFriend: isFriend,
    getRcmdFriends: getRcmdFriends
  };

}).call(this);
