// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, assert, debuglog, fs, path;

  debuglog = require("debug")("wanba_tools");

  assert = require("assert");

  fs = require('fs');

  path = require('path');


  /*
   * 玩吧的工具类（SDK）
   */

  WanbaTools = (function() {
    function WanbaTools(options) {
      var models_path;
      debuglog("LOG [wanba_tools::constructor] start");
      this.appid = options.appid;
      this.appkey = options.appkey;
      this.host = options.host;
      this.pf = options.pf || 'wanba_ts';
      this.format = options.format || "json";
      assert(this.appid, "missing wanba appid");
      assert(this.appkey, "missing wanba appkey");
      models_path = path.join(__dirname, './models');
      fs.readdirSync(models_path).forEach((function(_this) {
        return function(file) {
          var key, obj, v;
          obj = require("" + models_path + "/" + file);
          for (key in obj) {
            v = obj[key];
            _this[key] = v;
          }
        };
      })(this));
      return;
    }

    WanbaTools.prototype.setPf = function(pf) {
      return this.pf = pf;
    };

    WanbaTools.prototype.setFormat = function(format) {
      return this.format = format;
    };

    return WanbaTools;

  })();

  module.exports = WanbaTools;

}).call(this);
