// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    appid: "123456",
    appkey: "228bf094169a40a3bd188ba37ebe8723",
    host: "http://119.147.19.43",
    ps: "wanba_ts",
    format: "json"
  };

}).call(this);
