// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, config, method, params, should, wbt, wbtOptions, _;

  should = require("should");

  _ = require('underscore');

  config = require("../config/test_config");

  WanbaTools = require("../wanba_tools");

  wbtOptions = config;

  params = {
    openid: config.openid,
    openkey: config.openkey
  };

  wbt = new WanbaTools(wbtOptions);

  console.dir(wbt);

  method = "POST";

  describe("test relation", function() {
    before(function() {});
    describe("getAppFriends", function() {
      return it("should get app friends", function(done) {
        var options;
        options = {
          openid: params.openid,
          openkey: params.openkey
        };
        return wbt.getAppFriends(options, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
    describe("isFriend", function() {
      return it("should is friends", function(done) {
        var options;
        options = {
          openid: params.openid,
          openkey: params.openkey,
          fopenid: params.openid
        };
        return wbt.isFriend(options, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
    return describe("getAppFriends", function() {
      var options;
      options = {
        openid: params.openid,
        openkey: params.openkey,
        fopenid: params.openid
      };
      return it("should get app friends", function(done) {
        return wbt.getAppFriends(options, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
  });

}).call(this);
