// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, config, options, params, should, wbt, _;

  should = require("should");

  _ = require('underscore');

  config = require('../config/config');

  WanbaTools = require("../wanba_tools");

  options = config;

  params = {
    openid: "11111111111111111",
    openkey: "2222222222222222"
  };

  wbt = new WanbaTools(options);

  console.dir(wbt);

  describe("test relation", function() {
    before(function() {});
    return describe("getAppFriends", function() {
      return it("should get app friends", function(done) {
        return wbt.getAppFriends(params, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
  });

}).call(this);
