// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, config, method, options, params, should, wbt, _;

  should = require("should");

  _ = require('underscore');

  config = require('../config/config');

  WanbaTools = require("../wanba_tools");

  options = config;

  params = {
    openid: "11111111111111111",
    openkey: "2222222222222222"
  };

  wbt = new WanbaTools(options);

  console.dir(wbt);

  method = "POST";

  describe("test relation", function() {
    before(function() {});
    describe("getAppFriends", function() {
      return it("should get app friends", function(done) {
        return wbt.getAppFriends(params, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
    describe("isFriend", function() {
      return it("should is friends", function(done) {
        options = {
          openid: params.openid,
          openkey: params.openkey,
          fopenid: params.openid
        };
        return wbt.isFriend(params, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
    return describe("getAppFriends", function() {
      options = {
        openid: params.openid,
        openkey: params.openkey,
        fopenid: params.openid
      };
      return it("should get app friends", function(done) {
        return wbt.getAppFriends(options, method, function(err, result) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(result);
          return done();
        });
      });
    });
  });

}).call(this);
