// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, config, method, options, params, should, testSign, url, wbt, _;

  should = require("should");

  _ = require('underscore');

  config = require('../config/config');

  WanbaTools = require("../wanba_tools");

  options = {
    appid: config.appid,
    appkey: config.appkey
  };

  testSign = "FdJkiDYwMj5Aj1UG2RUPc83iokk=";

  url = '/v3/user/get_info';

  method = "GET";

  params = {
    openid: "11111111111111111",
    openkey: "2222222222222222",
    appid: config.appid,
    pf: "qzone",
    format: "json",
    userip: "112.90.139.30"
  };

  wbt = new WanbaTools(options);

  console.dir(wbt);

  describe("test signature", function() {
    before(function() {});
    return describe("makeSignature", function() {
      return it("should make signature", function(done) {
        var sign;
        sign = wbt.makeSignature(url, method, params);
        console.log("sign: " + sign);
        console.log(sign === testSign);
        return done();
      });
    });
  });

}).call(this);
