// Generated by CoffeeScript 1.8.0
(function() {
  var WanbaTools, config, method, params, should, wbt, wbtOptions, _;

  should = require("should");

  _ = require('underscore');

  config = require("../config/test_config");

  WanbaTools = require("../wanba_tools");

  wbtOptions = config;

  wbt = new WanbaTools(wbtOptions);

  console.dir(wbt);

  params = {
    openid: config.openid,
    openkey: config.openkey
  };

  method = 'POST';

  describe("test users", function() {
    before(function() {});
    return describe("getInfo", function() {
      return it("should get info", function(done) {
        var options;
        options = {
          openid: params.openid,
          openkey: params.openkey
        };
        return wbt.getInfo(options, method, function(err, info) {
          if (err != null) {
            console.error("ERROR:: " + err);
          }
          console.dir(info);
          return done();
        });
      });
    });
  });

}).call(this);
